baseURL: "https://danielwagner.at/"
languageCode: "en-us"
title: "Daniel Wagner e.U."
paginate: 5
theme: PaperMod

enableGitInfo: true
enableRobotsTXT: true
# buildDrafts: false
# buildFuture: false
# buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Daniel Wagner
  description: "Daniel Wagner e.U."
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    # favicon: "<link / abs url>"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"

  label:
    text: "Daniel Wagner e.U."
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Daniel Wagner
    subtitle: "Helping people improve"
    imageUrl: "img/profile-image.png"
    imageWidth: 200
    imageHeight: 200
    imageTitle: my image
    buttons:
      - name: About
        url: page/about
      - name: Posts
        url: posts
      - name: Projects
        url: projects
      # - name: Tags
      #   url: tags
      - name: Search
        url: search

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: email
      url: "mailto:daniel@danielwagner.at"
    - name: github
      url: "https://github.com/danielwagn3r"
    - name: gitlab
      url: "https://gitlab.com/danielwagn3r"
    - name: linkedin
      url: "https://www.linkedin.com/in/danielwagn3r"
    - name: facebook
      url: "https://www.facebook.com/daniel.wagn3r"
    - name: instagram
      url: "https://www.instagram.com/dani3lwagner"
    - name: mastodon
      url: "https://fedi.at/@danielwagn3r"
    - name: twitter
      url: "https://twitter.com/daniel_wagn3r"
    - name: rss
      url: "index.xml"

  analytics:
    # google:
    #   SiteVerificationTag: "XYZabc"
    # bing:
    #   SiteVerificationTag: "XYZabc"
    # yandex:
    #   SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/danielwagnerEU/danielwagnereu.github.io/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: about
      name: about
      url: /page/about/
      weight: 10
    - identifier: posts
      name: posts
      url: /posts/
      weight: 10
    - identifier: projects
      name: projects
      url: /projects/
      weight: 20
    # - identifier: categories
    #   name: categories
    #   url: /categories/
    #   weight: 30
    # - identifier: tags
    #   name: tags
    #   url: /tags/
    #   weight: 40
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 50
    - identifier: search
      name: search
      url: /search
      weight: 60

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
