baseURL = 'https://danielwagner.at/'
languageCode = 'de-at'
title = 'Daniel Wagner'
theme = 'beautifulhugo'

enableRobotsTXT = true
enableGitInfo = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = 'monokai'
    tabWidth = 4

[Params]
  commit = "https://github.com/danielwagnerEU/danielwagnereu.github.io/tree/"
  selfHosted = true
  subtitle = "Helping others improve"
  mainSections = ["post","posts"]
  logo = "img/logo.avif" # Expecting square dimensions
  favicon = "img/favicon.png"
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = false
  socialShare = true

  [Author]
    name = "Daniel Wagner"
    website = "https://danielwagner.at"
    email = "daniel@danielwagner.at"
    facebook = "daniel.wagn3r"
    instagram = "dani3lwagner"
    linkedin = "danielwagn3r"
    mastodon = "https://fedi.at/@danielwagn3r"
    github = "danielwagn3r"
    gitlab = "danielwagn3r"
    twitter = "daniel_wagn3r"

 [[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    identifier = "projects"
    name = "Projects"
    weight = 2

[[menu.main]]
    parent = "projects"
    name = "CoderDojo"
    url = "projects/coderdojo"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3