baseURL = 'https://danielwagner.at/'
languageCode = 'de-at'
title = 'Daniel Wagner'
theme = 'beautifulhugo'


enableGitInfo = true

[Params]
  commit = "https://github.com/danielwagnerEU/danielwagnereu.github.io/tree/"
  selfHosted = true
  subtitle = "Helping others improve"
  mainSections = ["post","posts"]
  logo = "img/logo.png" # Expecting square dimensions
  favicon = "img/favicon.png"
  rss = true
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true

  [Author]
    #name = "Daniel Wagner"
    website = "https://danielwagner.at"
    email = "daniel@danielwagner.at"
    facebook = "daniel.wagn3r"
    instagram = "dani3lwagner"
    linkedin = "danielwagn3r"
    mastodon = "https://fedi.at/@danielwagn3r"
    github = "danielwagn3r"
    gitlab = "danielwagn3r"
    twitter = "daniel_wagn3r"

 [[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3